---
- name: 'Install Woodpecker Server'
  hosts: 'woodpecker-server'
  gather_facts: true
  become: true

  roles:
    - role: 'johanneskastl.install_one_or_more_packages'
      packages_to_be_installed:
        - woodpecker-server
        - woodpecker-cli
