---

- name: 'Run playbook-all_nodes-bootstrap_python.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-bootstrap_python.yml

- name: 'Run playbook-all_nodes-create_a_vimrc.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-create_a_vimrc.yml

- name: 'Run playbook-all_nodes-install_tmux.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-install_tmux.yml

- name: 'Run playbook-all_nodes-minimal_tmux_configuration.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_tmux_configuration.yml

- name: 'Run playbook-all_nodes-minimal_bashrc.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_bashrc.yml

- name: 'Run playbook-all_nodes-add_Branch_devel_tools_building_repository.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-add_Branch_devel_tools_building_repository.yml

#
# server
#

- name: 'Run playbook-server-add_Branch_devel_tools_scm_repository.yml'
  ansible.builtin.import_playbook: playbook-server-add_Branch_devel_tools_scm_repository.yml

- name: 'Run playbook-server-install_forgejo.yml'
  ansible.builtin.import_playbook: playbook-server-install_forgejo.yml

- name: 'Run playbook-server-configure_and_start_forgejo.yml'
  ansible.builtin.import_playbook: playbook-server-configure_and_start_forgejo.yml

- name: 'Run playbook-server-install_woodpecker.yml'
  ansible.builtin.import_playbook: playbook-server-install_woodpecker.yml

- name: 'Run playbook-server-configure_and_start_woodpecker_server.yml'
  ansible.builtin.import_playbook: playbook-server-configure_and_start_woodpecker_server.yml

#
# agent
#

- name: 'Run playbook-agent-install_woodpecker_agent.yml'
  ansible.builtin.import_playbook: playbook-agent-install_woodpecker_agent.yml

- name: 'Run playbook-agent-configure_and_start_woodpecker_agent.yml'
  ansible.builtin.import_playbook: playbook-agent-configure_and_start_woodpecker_agent.yml
